### ISSUE TITLE
official mirror

### ISSUE THREAD

**Issue by 0-wiz-0** [keithjjones/libzip#1]
There is now an official mirror at https://github.com/nih-at/libzip

**Comment by keithjjones** [comment]
Awesome.  Do you know of a way I can make this a fork of yours?  Or is it just easier to delete and fork?

**Comment by 0-wiz-0** [comment]
Good question. No, I don't know that. Delete and re-fork will work, so if you don't have any history to lose, that's probably easiest.
Btw, do you have any local patches we should merge?

**Comment by keithjjones** [comment]
I do not.  I made that small change and sent it up to the official repository.  I think it was merged.  I did not check though.

**Comment by 0-wiz-0** [comment]
Yes, I did add your patch for the static cmake target.

**Comment by keithjjones** [comment]
Awesome.  I am going to delete this now.  Thanks!
